# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sticker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rsticker.proto\x12\x07sticker\">\n\x07Sticker\x12\x12\n\nplayername\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\x12\x0e\n\x06rarity\x18\x03 \x01(\x05\"\'\n\x13ListStickersRequest\x12\x10\n\x08username\x18\x01 \x01(\t2T\n\x0eStickerService\x12\x42\n\x0clist_of_user\x12\x1c.sticker.ListStickersRequest\x1a\x10.sticker.Sticker\"\x00\x30\x01\x62\x06proto3')



_STICKER = DESCRIPTOR.message_types_by_name['Sticker']
_LISTSTICKERSREQUEST = DESCRIPTOR.message_types_by_name['ListStickersRequest']
Sticker = _reflection.GeneratedProtocolMessageType('Sticker', (_message.Message,), {
  'DESCRIPTOR' : _STICKER,
  '__module__' : 'sticker_pb2'
  # @@protoc_insertion_point(class_scope:sticker.Sticker)
  })
_sym_db.RegisterMessage(Sticker)

ListStickersRequest = _reflection.GeneratedProtocolMessageType('ListStickersRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTSTICKERSREQUEST,
  '__module__' : 'sticker_pb2'
  # @@protoc_insertion_point(class_scope:sticker.ListStickersRequest)
  })
_sym_db.RegisterMessage(ListStickersRequest)

_STICKERSERVICE = DESCRIPTOR.services_by_name['StickerService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _STICKER._serialized_start=26
  _STICKER._serialized_end=88
  _LISTSTICKERSREQUEST._serialized_start=90
  _LISTSTICKERSREQUEST._serialized_end=129
  _STICKERSERVICE._serialized_start=131
  _STICKERSERVICE._serialized_end=215
# @@protoc_insertion_point(module_scope)
